jobs:
  dependencies:
    override:
      - npm install -g firebase-tools
  deployment:
    deploy:
      branch: master
      commands:
        - firebase deploy --project "mymarkdown2" --token "1/w1qvnmL6Y9q3uluzF3PV3-lXA1IBtRN1-SSVSaKo52I"